version: '3.8'

networks:
  backend_network:
    external: false

services:
  reviews:
    build: .
    container_name: reviews_service
    env_file:
      - .env.test
    networks:
      - backend_network
    depends_on:
      - reviews_db
    command: pytest

  reviews_db:
    image: postgres:15
    container_name: reviews_test_db
    restart: "no"
    environment:
      POSTGRES_DB: reviews_test_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - backend_network