version: '3.8'


networks:
  backend_network:
    external: false

services:
  reviews:
    build: .
    container_name: reviews_service
    env_file:
      - .env.prod
    ports:
      - "5002:5000"
    networks:
      - backend_network
    command: >
      sh -c "
        alembic revision --autogenerate -m 'initial' &&
        alembic upgrade head
      "