version: '3.8'

networks:
  backend_network:
    external: false

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Connection
      - "15672:15672" # Management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend_network

  reviews:
    build: .
    container_name: reviews_service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_ENV=testing
      - FLASK_APP=run.py
      - DEBUG=true
    networks:
      - backend_network
    depends_on:
      - reviews_db
      - rabbitmq
    command: pytest /tests/test_routes.py -v

  reviews_db:
    image: postgres:15
    container_name: reviews_test_db
    restart: "no"
    environment:
      POSTGRES_DB: reviews_test_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    networks:
      - backend_network