name: CI - Reviews Service

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Run tests with Docker Compose v2
      - name: Run tests
        run: |
          docker compose -f ${{ github.workspace }}/docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from reviews
          docker compose -f ${{ github.workspace }}/docker-compose.test.yml down -v
      
      # 3. Build final Docker image for Docker Hub
      - name: Build Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          IMAGE_NAME="$DOCKER_USERNAME/reviews-service:${GITHUB_SHA}"
          docker build -t "$IMAGE_NAME" .

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Push Docker image
      - name: Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          IMAGE_NAME="$DOCKER_USERNAME/reviews-service:${GITHUB_SHA}"
          docker push "$IMAGE_NAME"