name: CI - Reviews Service

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run tests with docker-compose
      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from reviews
          docker-compose -f docker-compose.test.yml down -v 

      # Build final image for Docker Hub
      - name: Build Docker image for registry
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/reviews-service:${GITHUB_SHA}"
          docker build -t "$IMAGE_NAME" .

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image
      - name: Push Docker image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/reviews-service:${GITHUB_SHA}"
          docker push "$IMAGE_NAME"