name: CI - Reviews-Dev

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Run tests with Docker Compose v2
      - name: Run Unit tests
        run: |
          docker compose -f ${{ github.workspace }}/docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from reviews
          docker compose -f ${{ github.workspace }}/docker-compose.test.yml down -v
      
